

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "public";






CREATE OR REPLACE FUNCTION "public"."get_page_parents"("page_id" bigint) RETURNS TABLE("id" bigint, "parent_page_id" bigint, "path" "text", "meta" "jsonb")
    LANGUAGE "sql"
    AS $$
  with recursive chain as (
    select *
    from nods_page 
    where id = page_id

    union all

    select child.*
      from nods_page as child
      join chain on chain.parent_page_id = child.id 
  )
  select id, parent_page_id, path, meta
  from chain;
$$;


ALTER FUNCTION "public"."get_page_parents"("page_id" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."match_page_sections"("embedding" "public"."vector", "match_threshold" double precision, "match_count" integer, "min_content_length" integer) RETURNS TABLE("id" bigint, "page_id" bigint, "slug" "text", "heading" "text", "content" "text", "similarity" double precision)
    LANGUAGE "plpgsql"
    AS $$
#variable_conflict use_variable
begin
  return query
  select
    nods_page_section.id,
    nods_page_section.page_id,
    nods_page_section.slug,
    nods_page_section.heading,
    nods_page_section.content,
    (nods_page_section.embedding <#> embedding) * -1 as similarity
  from nods_page_section

  -- We only care about sections that have a useful amount of content
  where length(nods_page_section.content) >= min_content_length

  -- The dot product is negative because of a Postgres limitation, so we negate it
  and (nods_page_section.embedding <#> embedding) * -1 > match_threshold

  -- OpenAI embeddings are normalized to length 1, so
  -- cosine similarity and dot product will produce the same results.
  -- Using dot product which can be computed slightly faster.
  --
  -- For the different syntaxes, see https://github.com/pgvector/pgvector
  order by nods_page_section.embedding <#> embedding
  
  limit match_count;
end;
$$;


ALTER FUNCTION "public"."match_page_sections"("embedding" "public"."vector", "match_threshold" double precision, "match_count" integer, "min_content_length" integer) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admin" (
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."admin" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."archives" (
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "year" "text" NOT NULL,
    "month" "text" NOT NULL,
    "week" "text" NOT NULL,
    "content" "text",
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text")
);


ALTER TABLE "public"."archives" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."docs_page" (
    "id" bigint NOT NULL,
    "path" "text" NOT NULL,
    "checksum" "text",
    "meta" "jsonb",
    "type" "text",
    "source" "text",
    "parent_page_id" bigint
);


ALTER TABLE "public"."docs_page" OWNER TO "postgres";


ALTER TABLE "public"."docs_page" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."docs_page_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."docs_page_section" (
    "id" bigint NOT NULL,
    "content" "text",
    "token_count" integer,
    "embedding" "public"."vector"(1536),
    "slug" "text",
    "heading" "text",
    "page_id" bigint
);


ALTER TABLE "public"."docs_page_section" OWNER TO "postgres";


ALTER TABLE "public"."docs_page_section" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."docs_page_section_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."document_copies" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "copy_g_id" "text",
    "doc_details" "json"
);


ALTER TABLE "public"."document_copies" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."documents" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "google_id" "text",
    "latest_copy_g_id" "text",
    "latest_copy_details" "json",
    "all_copy_ids" "json" DEFAULT '[]'::"json",
    "sharing_status" "text",
    "previous_sharing_status" "text",
    "document_text" "text",
    "doc_type" "text",
    "url" "text",
    "workgroup" "text",
    "entity" "text",
    "title" "text",
    "metadata" "json"
);


ALTER TABLE "public"."documents" OWNER TO "postgres";


COMMENT ON TABLE "public"."documents" IS 'This is a duplicate of documents_test';



CREATE TABLE IF NOT EXISTS "public"."documents_test" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "google_id" "text",
    "latest_copy_g_id" "text",
    "latest_copy_details" "json",
    "all_copy_ids" "json" DEFAULT '[]'::"json",
    "sharing_status" "text",
    "previous_sharing_status" "text",
    "document_text" "text",
    "doc_type" "text",
    "url" "text"
);


ALTER TABLE "public"."documents_test" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meetingsummaries" (
    "meeting_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "template" "text",
    "date" timestamp without time zone,
    "workgroup_id" "uuid",
    "summary" "json",
    "name" "text" DEFAULT ''::"text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "confirmed" boolean DEFAULT false,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."meetingsummaries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meetingsummaries_test" (
    "meeting_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "template" "text",
    "date" timestamp without time zone,
    "workgroup_id" "uuid",
    "summary" "json",
    "name" "text" DEFAULT ''::"text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "confirmed" boolean DEFAULT false,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."meetingsummaries_test" OWNER TO "postgres";


COMMENT ON TABLE "public"."meetingsummaries_test" IS 'This is a duplicate of meetingsummaries';



CREATE TABLE IF NOT EXISTS "public"."missingsummaries" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "workgroup_id" "uuid",
    "workgroup" "text",
    "meeting_date" "text",
    "status" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "updated_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "type" "text"
);


ALTER TABLE "public"."missingsummaries" OWNER TO "postgres";


ALTER TABLE "public"."missingsummaries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."missing_summaries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."names" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "approved" boolean
);


ALTER TABLE "public"."names" OWNER TO "postgres";


ALTER TABLE "public"."names" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."names_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."nods_page" (
    "id" bigint NOT NULL,
    "parent_page_id" bigint,
    "path" "text" NOT NULL,
    "checksum" "text",
    "meta" "jsonb",
    "type" "text",
    "source" "text"
);


ALTER TABLE "public"."nods_page" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."nods_page_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."nods_page_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."nods_page_id_seq" OWNED BY "public"."nods_page"."id";



CREATE TABLE IF NOT EXISTS "public"."nods_page_section" (
    "id" bigint NOT NULL,
    "page_id" bigint NOT NULL,
    "content" "text",
    "token_count" integer,
    "embedding" "public"."vector"(1536),
    "slug" "text",
    "heading" "text"
);


ALTER TABLE "public"."nods_page_section" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."nods_page_section_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."nods_page_section_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."nods_page_section_id_seq" OWNED BY "public"."nods_page_section"."id";



CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tag" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "type" "text"
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_topics_covered_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "name" "text",
    "discord_roles" "json",
    "app_role" "text",
    "avatar_url" "text",
    "global_name" "text",
    "full_name" "text"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."workgroups" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "workgroup" "text",
    "workgroup_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "last_meeting_id" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "preferred_template" "json"
);


ALTER TABLE "public"."workgroups" OWNER TO "postgres";


ALTER TABLE ONLY "public"."nods_page" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."nods_page_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."nods_page_section" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."nods_page_section_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."archives"
    ADD CONSTRAINT "archives_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."docs_page"
    ADD CONSTRAINT "docs_page_path_key" UNIQUE ("path");



ALTER TABLE ONLY "public"."docs_page"
    ADD CONSTRAINT "docs_page_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."docs_page_section"
    ADD CONSTRAINT "docs_page_section_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."document_copies"
    ADD CONSTRAINT "document_copies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."documents_test"
    ADD CONSTRAINT "documents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."documents"
    ADD CONSTRAINT "documents_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meetingsummaries"
    ADD CONSTRAINT "meetingsummaries_pkey" PRIMARY KEY ("meeting_id");



ALTER TABLE ONLY "public"."meetingsummaries_test"
    ADD CONSTRAINT "meetingsummaries_test_name_date_workgroup_id_user_id_key" UNIQUE ("name", "date", "workgroup_id", "user_id");



ALTER TABLE ONLY "public"."meetingsummaries_test"
    ADD CONSTRAINT "meetingsummaries_test_pkey" PRIMARY KEY ("meeting_id");



ALTER TABLE ONLY "public"."missingsummaries"
    ADD CONSTRAINT "missing_summaries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."names"
    ADD CONSTRAINT "names_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."nods_page"
    ADD CONSTRAINT "nods_page_path_key" UNIQUE ("path");



ALTER TABLE ONLY "public"."nods_page"
    ADD CONSTRAINT "nods_page_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."nods_page_section"
    ADD CONSTRAINT "nods_page_section_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_topics_covered_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."names"
    ADD CONSTRAINT "unique_name" UNIQUE ("name");



ALTER TABLE ONLY "public"."meetingsummaries"
    ADD CONSTRAINT "unique_name_date_workgroup_user" UNIQUE ("name", "date", "workgroup_id", "user_id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "unique_tag_type" UNIQUE ("tag", "type");



ALTER TABLE ONLY "public"."missingsummaries"
    ADD CONSTRAINT "unique_workgroup_meeting_type" UNIQUE ("workgroup_id", "meeting_date", "type");



ALTER TABLE ONLY "public"."archives"
    ADD CONSTRAINT "unique_year_month_week" UNIQUE ("year", "month", "week");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."workgroups"
    ADD CONSTRAINT "workgroups_pkey" PRIMARY KEY ("workgroup_id");



ALTER TABLE ONLY "public"."docs_page"
    ADD CONSTRAINT "docs_page_parent_page_id_fkey" FOREIGN KEY ("parent_page_id") REFERENCES "public"."docs_page"("id");



ALTER TABLE ONLY "public"."docs_page_section"
    ADD CONSTRAINT "docs_page_section_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."docs_page"("id");



ALTER TABLE ONLY "public"."meetingsummaries_test"
    ADD CONSTRAINT "meetingsummaries_test_workgroup_id_fkey" FOREIGN KEY ("workgroup_id") REFERENCES "public"."workgroups"("workgroup_id");



ALTER TABLE ONLY "public"."meetingsummaries"
    ADD CONSTRAINT "meetingsummaries_workgroup_id_fkey" FOREIGN KEY ("workgroup_id") REFERENCES "public"."workgroups"("workgroup_id");



ALTER TABLE ONLY "public"."missingsummaries"
    ADD CONSTRAINT "missingsummaries_workgroup_id_fkey" FOREIGN KEY ("workgroup_id") REFERENCES "public"."workgroups"("workgroup_id");



ALTER TABLE ONLY "public"."nods_page"
    ADD CONSTRAINT "nods_page_parent_page_id_fkey" FOREIGN KEY ("parent_page_id") REFERENCES "public"."nods_page"("id");



ALTER TABLE ONLY "public"."nods_page_section"
    ADD CONSTRAINT "nods_page_section_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."nods_page"("id") ON DELETE CASCADE;



CREATE POLICY "Access to authenticated users only" ON "public"."users" TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "Allow update for authenticated users" ON "public"."tags" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Enable all for authenticated users only" ON "public"."missingsummaries" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."names" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."tags" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "Enable read access for all users" ON "public"."admin" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."document_copies" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."documents_test" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."meetingsummaries" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."missingsummaries" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."names" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."tags" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."users" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."workgroups" FOR SELECT USING (true);



ALTER TABLE "public"."admin" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."document_copies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."documents" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."documents_test" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meetingsummaries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."missingsummaries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."names" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."nods_page" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."nods_page_section" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "priv_user_policy" ON "public"."workgroups" TO "authenticated" USING (("auth"."uid"() IN ( SELECT "admin"."user_id"
   FROM "public"."admin"))) WITH CHECK (("auth"."uid"() IN ( SELECT "admin"."user_id"
   FROM "public"."admin")));



CREATE POLICY "privileged_user_policy" ON "public"."meetingsummaries" TO "authenticated" USING (("auth"."uid"() IN ( SELECT "admin"."user_id"
   FROM "public"."admin"))) WITH CHECK (("auth"."uid"() IN ( SELECT "admin"."user_id"
   FROM "public"."admin")));



ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "user_owns_row_policy" ON "public"."meetingsummaries" TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "user_owns_row_policy2" ON "public"."workgroups" TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."workgroups" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_in"("cstring", "oid", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."vector_in"("cstring", "oid", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_in"("cstring", "oid", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_out"("public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_out"("public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_out"("public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_recv"("internal", "oid", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."vector_recv"("internal", "oid", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_recv"("internal", "oid", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_send"("public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_send"("public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_send"("public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_typmod_in"("cstring"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."vector_typmod_in"("cstring"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_typmod_in"("cstring"[]) TO "service_role";



GRANT ALL ON FUNCTION "public"."array_to_vector"(real[], integer, boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."array_to_vector"(real[], integer, boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."array_to_vector"(real[], integer, boolean) TO "service_role";



GRANT ALL ON FUNCTION "public"."array_to_vector"(double precision[], integer, boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."array_to_vector"(double precision[], integer, boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."array_to_vector"(double precision[], integer, boolean) TO "service_role";



GRANT ALL ON FUNCTION "public"."array_to_vector"(integer[], integer, boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."array_to_vector"(integer[], integer, boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."array_to_vector"(integer[], integer, boolean) TO "service_role";



GRANT ALL ON FUNCTION "public"."array_to_vector"(numeric[], integer, boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."array_to_vector"(numeric[], integer, boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."array_to_vector"(numeric[], integer, boolean) TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_to_float4"("public"."vector", integer, boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."vector_to_float4"("public"."vector", integer, boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_to_float4"("public"."vector", integer, boolean) TO "service_role";



GRANT ALL ON FUNCTION "public"."vector"("public"."vector", integer, boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."vector"("public"."vector", integer, boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector"("public"."vector", integer, boolean) TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."cosine_distance"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."cosine_distance"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."cosine_distance"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."get_page_parents"("page_id" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."get_page_parents"("page_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_page_parents"("page_id" bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."inner_product"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."inner_product"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."inner_product"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."ivfflathandler"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."ivfflathandler"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."ivfflathandler"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."l2_distance"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."l2_distance"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."l2_distance"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."match_page_sections"("embedding" "public"."vector", "match_threshold" double precision, "match_count" integer, "min_content_length" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."match_page_sections"("embedding" "public"."vector", "match_threshold" double precision, "match_count" integer, "min_content_length" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."match_page_sections"("embedding" "public"."vector", "match_threshold" double precision, "match_count" integer, "min_content_length" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_accum"(double precision[], "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_accum"(double precision[], "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_accum"(double precision[], "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_add"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_add"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_add"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_avg"(double precision[]) TO "anon";
GRANT ALL ON FUNCTION "public"."vector_avg"(double precision[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_avg"(double precision[]) TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_cmp"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_cmp"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_cmp"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_combine"(double precision[], double precision[]) TO "anon";
GRANT ALL ON FUNCTION "public"."vector_combine"(double precision[], double precision[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_combine"(double precision[], double precision[]) TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_dims"("public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_dims"("public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_dims"("public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_eq"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_eq"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_eq"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_ge"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_ge"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_ge"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_gt"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_gt"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_gt"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_l2_squared_distance"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_l2_squared_distance"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_l2_squared_distance"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_le"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_le"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_le"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_lt"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_lt"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_lt"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_ne"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_ne"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_ne"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_negative_inner_product"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_negative_inner_product"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_negative_inner_product"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_norm"("public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_norm"("public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_norm"("public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_spherical_distance"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_spherical_distance"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_spherical_distance"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."vector_sub"("public"."vector", "public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."vector_sub"("public"."vector", "public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."vector_sub"("public"."vector", "public"."vector") TO "service_role";



GRANT ALL ON FUNCTION "public"."avg"("public"."vector") TO "anon";
GRANT ALL ON FUNCTION "public"."avg"("public"."vector") TO "authenticated";
GRANT ALL ON FUNCTION "public"."avg"("public"."vector") TO "service_role";


















GRANT ALL ON TABLE "public"."admin" TO "anon";
GRANT ALL ON TABLE "public"."admin" TO "authenticated";
GRANT ALL ON TABLE "public"."admin" TO "service_role";



GRANT ALL ON TABLE "public"."archives" TO "anon";
GRANT ALL ON TABLE "public"."archives" TO "authenticated";
GRANT ALL ON TABLE "public"."archives" TO "service_role";



GRANT ALL ON TABLE "public"."docs_page" TO "anon";
GRANT ALL ON TABLE "public"."docs_page" TO "authenticated";
GRANT ALL ON TABLE "public"."docs_page" TO "service_role";



GRANT ALL ON SEQUENCE "public"."docs_page_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."docs_page_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."docs_page_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."docs_page_section" TO "anon";
GRANT ALL ON TABLE "public"."docs_page_section" TO "authenticated";
GRANT ALL ON TABLE "public"."docs_page_section" TO "service_role";



GRANT ALL ON SEQUENCE "public"."docs_page_section_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."docs_page_section_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."docs_page_section_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."document_copies" TO "anon";
GRANT ALL ON TABLE "public"."document_copies" TO "authenticated";
GRANT ALL ON TABLE "public"."document_copies" TO "service_role";



GRANT ALL ON TABLE "public"."documents" TO "anon";
GRANT ALL ON TABLE "public"."documents" TO "authenticated";
GRANT ALL ON TABLE "public"."documents" TO "service_role";



GRANT ALL ON TABLE "public"."documents_test" TO "anon";
GRANT ALL ON TABLE "public"."documents_test" TO "authenticated";
GRANT ALL ON TABLE "public"."documents_test" TO "service_role";



GRANT ALL ON TABLE "public"."meetingsummaries" TO "anon";
GRANT ALL ON TABLE "public"."meetingsummaries" TO "authenticated";
GRANT ALL ON TABLE "public"."meetingsummaries" TO "service_role";



GRANT ALL ON TABLE "public"."meetingsummaries_test" TO "anon";
GRANT ALL ON TABLE "public"."meetingsummaries_test" TO "authenticated";
GRANT ALL ON TABLE "public"."meetingsummaries_test" TO "service_role";



GRANT ALL ON TABLE "public"."missingsummaries" TO "anon";
GRANT ALL ON TABLE "public"."missingsummaries" TO "authenticated";
GRANT ALL ON TABLE "public"."missingsummaries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."missing_summaries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."missing_summaries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."missing_summaries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."names" TO "anon";
GRANT ALL ON TABLE "public"."names" TO "authenticated";
GRANT ALL ON TABLE "public"."names" TO "service_role";



GRANT ALL ON SEQUENCE "public"."names_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."names_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."names_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."nods_page" TO "anon";
GRANT ALL ON TABLE "public"."nods_page" TO "authenticated";
GRANT ALL ON TABLE "public"."nods_page" TO "service_role";



GRANT ALL ON SEQUENCE "public"."nods_page_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."nods_page_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."nods_page_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."nods_page_section" TO "anon";
GRANT ALL ON TABLE "public"."nods_page_section" TO "authenticated";
GRANT ALL ON TABLE "public"."nods_page_section" TO "service_role";



GRANT ALL ON SEQUENCE "public"."nods_page_section_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."nods_page_section_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."nods_page_section_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_topics_covered_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_topics_covered_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_topics_covered_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON TABLE "public"."workgroups" TO "anon";
GRANT ALL ON TABLE "public"."workgroups" TO "authenticated";
GRANT ALL ON TABLE "public"."workgroups" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























