-- Create tables for seed data
-- This migration creates the tables needed for the seed.sql file

-- Create workgroups table
CREATE TABLE IF NOT EXISTS "public"."workgroups" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "workgroup" "text",
    "workgroup_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "last_meeting_id" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "preferred_template" "json"
);

-- Create meetingsummaries table
CREATE TABLE IF NOT EXISTS "public"."meetingsummaries" (
    "meeting_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "template" "text",
    "date" timestamp without time zone,
    "workgroup_id" "uuid",
    "summary" "json",
    "name" "text" DEFAULT ''::"text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "confirmed" boolean DEFAULT false,
    "updated_at" timestamp with time zone DEFAULT "now"()
);

-- Create names table
CREATE TABLE IF NOT EXISTS "public"."names" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "approved" boolean
);

-- Add identity to names.id (idempotent - only if not already an identity)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute 
        WHERE attrelid = 'public.names'::regclass 
        AND attname = 'id' 
        AND attidentity != ''
    ) THEN
        ALTER TABLE "public"."names" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Create tags table
CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tag" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "type" "text"
);

-- Add identity to tags.id (idempotent - only if not already an identity)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute 
        WHERE attrelid = 'public.tags'::regclass 
        AND attname = 'id' 
        AND attidentity != ''
    ) THEN
        ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Add primary key constraints
ALTER TABLE ONLY "public"."workgroups"
    ADD CONSTRAINT "workgroups_pkey" PRIMARY KEY ("workgroup_id");

ALTER TABLE ONLY "public"."meetingsummaries"
    ADD CONSTRAINT "meetingsummaries_pkey" PRIMARY KEY ("meeting_id");

ALTER TABLE ONLY "public"."names"
    ADD CONSTRAINT "names_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_topics_covered_pkey" PRIMARY KEY ("id");

-- Add unique constraints
ALTER TABLE ONLY "public"."names"
    ADD CONSTRAINT "unique_name" UNIQUE ("name");

ALTER TABLE ONLY "public"."meetingsummaries"
    ADD CONSTRAINT "unique_name_date_workgroup_user" UNIQUE ("name", "date", "workgroup_id", "user_id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "unique_tag_type" UNIQUE ("tag", "type");

-- Add foreign key constraints
ALTER TABLE ONLY "public"."meetingsummaries"
    ADD CONSTRAINT "meetingsummaries_workgroup_id_fkey" FOREIGN KEY ("workgroup_id") REFERENCES "public"."workgroups"("workgroup_id");
